config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  # get 'components/automation'
  get 'new_movement/tag'
  
  resources :activities do
    resources :wishes
    resources :incomes, except: %i[ new create ]
    resources :expenses, except: %i[ new create ]
    get 'income/new', to: 'new_movement#base_step', defaults: { type: 'income' }
    get 'expense/new', to: 'new_movement#base_step', defaults: { type: 'expense' }
    get 'new_movement/back'
    post 'new_movement/base_step'
    post 'new_movement/configuration_step'
  end


  devise_for :accounts, path: 'auth', controllers: {
                                                    sessions: 'accounts/sessions',
                                                    registrations: 'accounts/registrations'
                                                  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount GoodJob::Engine => 'good_job'
  mount ActionCable.server => '/cable'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :activity
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: %i[ show edit update destroy ]

  # GET /wishes or /wishes.json
  def index
    @wishes = Wish.all
  end

  # GET /wishes/1 or /wishes/1.json
  def show
  end

  # GET /wishes/new
  def new
    @wish = Wish.new
  end

  # GET /wishes/1/edit
  def edit
  end

  # POST /wishes or /wishes.json
  def create
    @wish = Wish.new(wish_params)

    respond_to do |format|
      if @wish.save
        format.html { redirect_to wish_url(@wish), notice: "Wish was successfully created." }
        format.json { render :show, status: :created, location: @wish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishes/1 or /wishes/1.json
  def update
    respond_to do |format|
      if @wish.update(wish_params)
        format.html { redirect_to wish_url(@wish), notice: "Wish was successfully updated." }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1 or /wishes/1.json
  def destroy
    @wish.destroy!

    respond_to do |format|
      format.html { redirect_to wishes_url, notice: "Wish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wish_params
      params.require(:wish).permit(:name, :description, :estimation, :priority, :activity_id)
    end
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/wishes/_form.html.erb
<%= form_with(model: wish) do |form| %>
  <% if wish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
        <% wish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :estimation, style: "display: block" %>
    <%= form.number_field :estimation %>
  </div>

  <div>
    <%= form.label :priority, style: "display: block" %>
    <%= form.text_field :priority %>
  </div>

  <div>
    <%= form.label :activity_id, style: "display: block" %>
    <%= form.text_field :activity_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wishes/_wish.html.erb
<div id="<%= dom_id wish %>">
  <p>
    <strong>Name:</strong>
    <%= wish.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= wish.description %>
  </p>

  <p>
    <strong>Estimation:</strong>
    <%= wish.estimation %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= wish.priority %>
  </p>

  <p>
    <strong>Activity:</strong>
    <%= wish.activity_id %>
  </p>

</div>

app/views/wishes/edit.html.erb
<h1>Editing wish</h1>

<%= render "form", wish: @wish %>

<br>

<div>
  <%= link_to "Show this wish", @wish %> |
  <%= link_to "Back to wishes", wishes_path %>
</div>

app/views/wishes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wishes</h1>

<div id="wishes">
  <% @wishes.each do |wish| %>
    <%= render wish %>
    <p>
      <%= link_to "Show this wish", wish %>
    </p>
  <% end %>
</div>

<%= link_to "New wish", new_wish_path %>

app/views/wishes/new.html.erb
<h1>New wish</h1>

<%= render "form", wish: @wish %>

<br>

<div>
  <%= link_to "Back to wishes", wishes_path %>
</div>

app/views/wishes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wish %>

<div>
  <%= link_to "Edit this wish", edit_wish_path(@wish) %> |
  <%= link_to "Back to wishes", wishes_path %>

  <%= button_to "Destroy this wish", @wish, method: :delete %>
</div>