config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  # get 'components/automation'
  get 'new_movement/tag'
  
  resources :activities do
    resources :wishes
    resources :incomes, except: %i[ new create ]
    resources :expenses, except: %i[ new create ]
    get 'income/new', to: 'new_movement#base_step', defaults: { type: 'income' }
    get 'expense/new', to: 'new_movement#base_step', defaults: { type: 'expense' }
    get 'new_movement/back'
    post 'new_movement/base_step'
    post 'new_movement/configuration_step'
  end


  devise_for :accounts, path: 'auth', controllers: {
                                                    sessions: 'accounts/sessions',
                                                    registrations: 'accounts/registrations'
                                                  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount GoodJob::Engine => 'good_job'
  mount ActionCable.server => '/cable'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :activity_participants
  has_many :activities, through: :activity_participants
  has_many :notifications, as: :recipient, dependent: :destroy, class_name: 'Noticed::Notification'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/activity.rb
class Activity < ApplicationRecord
  ## Summary
  # The `Activity` class represents an activity and has various functionalities related to it, such as validations, associations, and tracking changes.
  # It also has methods to add and subtract amounts from the balance field.

  ## Fields
  # - `name`: A required field that represents the name of the activity.
  # - `start_date`: A required field that represents the start date of the activity.
  # - `balance`: A field that represents the balance of the activity, which can be updated using the `add` and `subtract` methods.

  ## Validations
  validates :name, :start_date, presence: true

  ## Associations
  has_many :activity_participants
  has_many :accounts, through: :activity_participants
  has_many :incomes

  ## Tracking Changes
  has_paper_trail only: [:balance], on: [:create, :update]

  ## Public Methods

  # Adds the specified `amount` to the `balance` field of the activity.
  #
  # @param amount [Numeric] The amount to be added to the balance.
  def add(amount)
    self.balance += amount
  end

  # Subtracts the specified `amount` from the `balance` field of the activity.
  #
  # @param amount [Numeric] The amount to be subtracted from the balance.
  def substract(amount)
    self.balance -= amount
  end
end

app/models/activity_participant.rb
class ActivityParticipant < ApplicationRecord
  belongs_to :activity
  belongs_to :account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/automation.rb
class Automation < ApplicationRecord
  belongs_to :configuration
  belongs_to :activity

  scope :jobs_to_run, -> { where(next_execution: Date.today.all_day) }
end

app/models/config_exception.rb
class ConfigException < ApplicationRecord
  belongs_to :configuration
end

app/models/configuration.rb
class Configuration < ApplicationRecord
  BASE_OPTIONS = %w[daily weekly fortnightly monthly quarterly].freeze

  EXCEPTION_OPTIONS = %w[weekend holiday day month].freeze

  COUNTRY_NAMES = {
    'US' => 'United States',
    'BR' => 'Brazil',
    'FR' => 'France',
    'UK' => 'United Kingdom',
    'SA' => 'Saudi Arabia',
    'IN' => 'India',
    'MG' => 'Madagascar',
    'JP' => 'Japan',
    'MA' => 'Morocco',
    'CI' => 'Ivory Coast'
  }.freeze
  
  HOLIDAY_POLICY_COUNTRIES = %w[US BR FR UK SA IN MG JP MA CI].map { |iso| [COUNTRY_NAMES[iso], iso] }.freeze

  has_many :config_exceptions
end

app/models/currency.rb
class Currency < ApplicationRecord
end

app/models/expense.rb
class Expense < Movement
end

app/models/income.rb
class Income < Movement
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :activity
end

app/models/user_currency.rb
class UserCurrency < ApplicationRecord
  belongs_to :currency
  belongs_to :account
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :activity
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/new_movement_helper.rb
module NewMovementHelper
  def holiday_select_tag
    <<~ERB
      <%= label_tag :holiday_exceptions, "Policy (#{Date.today.year} official infos)", class: ['required'] %>
      <%= select_tag(:holiday_exceptions,
                      options_for_select(Configuration::HOLIDAY_POLICY_COUNTRIES),
                      class: ['w-2/3', 'max-w-sm'],
                      required: true,
                      prompt: "Select value(s)") %>
    ERB
  end

  def day_select_tag
    <<~ERB
      <%= label_tag :day_exceptions, 'Day(s) exception', class: ['required'] %>
      <%= select_tag(:day_exceptions,
                      options_for_select(Date::DAYNAMES),
                      class: ['w-2/3', 'max-w-sm'],
                      required: true,
                      prompt: "Select value(s)") %>
    ERB
  end

  def month_select_tag
    <<~ERB
      <%= label_tag :month_exceptions, 'Month(s) exception', class: ['required'] %>
      <%= select_tag(:month_exceptions,
                      options_for_select(Date::MONTHNAMES.compact),
                      class: ['w-2/3', 'max-w-sm'],
                      required: true,
                      prompt: "Select value(s)") %>
    ERB
  end
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Harena</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body data-theme='business'>
    <div class="toast toast-top toast-center">
      <% if flash.alert %>
        <div class="alert alert-info">
          <span><%= flash.alert %></span>
        </div>
      <% end %>

      <% if flash.notice %>
        <div class="alert alert-success">
          <span><%= flash.notice %></span>
        </div>
      <% end %>
    </div>


    <%= render 'shared/navbar' %>

    <%= yield %>

    <%= render 'shared/footer' %>

    <%= console %>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authenticate | Harena</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body data-theme='corporate'>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 bg-base-200 text-base-content rounded">
  <nav class="grid grid-flow-col gap-4">
    <a class="link link-hover">About us</a>
    <a class="link link-hover">Contact</a>
    <a class="link link-hover">Jobs</a>
    <a class="link link-hover">Press kit</a>
  </nav> 
  <nav>
    <div class="grid grid-flow-col gap-4">
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a>
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a>
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
    </div>
  </nav> 
  <aside>
    <p>Copyright © 2024 - All right reserved by ACME Industries Ltd</p>
  </aside>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar bg-primary">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
      </div>

      <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-primary rounded-box w-52">
        <li><a>Homepage</a></li>
        <li><a>Portfolio</a></li>
        <li><a>About</a></li>
      </ul>
    </div>
  </div>

  <div class="navbar-center">
    <a class="text-xl" href='/'>Harena</a>
  </div>

  <div class="navbar-end space-x-6 px-4">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>

    <% if current_account %>
      <%= turbo_stream_from 'notification_panel' %>
      <%= render partial: "components/ui/notification_dropdown",
                 locals: {notifications: @notifications} %>
      <%= link_to "Sign out", destroy_account_session_path, data: {turbo_method: :delete} %>
    <% else %>
      <%= link_to "Sign in", new_account_session_path %>
    <% end %>

    <%= render 'components/ui/theme_controller' %>
  </div>
</div>