config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  # get 'components/automation'
  get 'new_movement/tag'
  
  resources :activities do
    resources :wishes
    resources :incomes, except: %i[ new create ]
    resources :expenses, except: %i[ new create ]
    get 'income/new', to: 'new_movement#base_step', defaults: { type: 'income' }
    get 'expense/new', to: 'new_movement#base_step', defaults: { type: 'expense' }
    get 'new_movement/back'
    post 'new_movement/base_step'
    post 'new_movement/configuration_step'
  end


  devise_for :accounts, path: 'auth', controllers: {
                                                    sessions: 'accounts/sessions',
                                                    registrations: 'accounts/registrations'
                                                  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount GoodJob::Engine => 'good_job'
  mount ActionCable.server => '/cable'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
  ## Summary
  # The `Activity` class represents an activity and has various functionalities related to it, such as validations, associations, and tracking changes.
  # It also has methods to add and subtract amounts from the balance field.

  ## Fields
  # - `name`: A required field that represents the name of the activity.
  # - `start_date`: A required field that represents the start date of the activity.
  # - `balance`: A field that represents the balance of the activity, which can be updated using the `add` and `subtract` methods.

  ## Validations
  validates :name, :start_date, presence: true

  ## Associations
  has_many :activity_participants
  has_many :accounts, through: :activity_participants
  has_many :incomes

  ## Tracking Changes
  has_paper_trail only: [:balance], on: [:create, :update]

  ## Public Methods

  # Adds the specified `amount` to the `balance` field of the activity.
  #
  # @param amount [Numeric] The amount to be added to the balance.
  def add(amount)
    self.balance += amount
  end

  # Subtracts the specified `amount` from the `balance` field of the activity.
  #
  # @param amount [Numeric] The amount to be subtracted from the balance.
  def substract(amount)
    self.balance -= amount
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_account!
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end
  
  # GET /activities/1/edit
  def edit
  end
  
  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    debugger
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy!
    
    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  def info_for_paper_trail
    super.merge({comment: params[:comment]})
  end
  
  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(:name, :description, :start_date, :balance)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>">
  <p>
    <strong>Name:</strong>
    <%= activity.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= activity.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= activity.start_date %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= activity.balance %>
  </p>

</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.text_field :balance %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <%
=begin%>
 <div>
    <%= form.fields_for :comment do |comment_form| %>
        <%= comment_form.label :comment, style: "display: block" %>
        <%= comment_form.text_area :comment %>
    <% end %>
  </div> 
<%
=end%>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Activities</h1>

<div id="activities">
  <% @activities.each do |activity| %>
    <%= render activity %>
    <p>
      <%= link_to "Show this activity", activity %>
    </p>
  <% end %>
</div>

<%= link_to "New activity", new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%= link_to "Edit this activity", edit_activity_path(@activity) %> |
  <%= link_to "Back to activities", activities_path %>
  <%= link_to "Activity expense", activity_expense_new_path(@activity), class: ['btn', 'btn-active', 'btn-secondaryz'] %>
  <%= link_to "New activity income", activity_income_new_path(@activity), class: ['btn', 'btn-active', 'btn-primary'] %>

  <%= button_to "Destroy this activity", @activity, method: :delete %>
</div>