config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  # get 'components/automation'
  get 'new_movement/tag'
  
  resources :activities do
    resources :wishes
    resources :incomes, except: %i[ new create ]
    resources :expenses, except: %i[ new create ]
    get 'income/new', to: 'new_movement#base_step', defaults: { type: 'income' }
    get 'expense/new', to: 'new_movement#base_step', defaults: { type: 'expense' }
    get 'new_movement/back'
    post 'new_movement/base_step'
    post 'new_movement/configuration_step'
  end


  devise_for :accounts, path: 'auth', controllers: {
                                                    sessions: 'accounts/sessions',
                                                    registrations: 'accounts/registrations'
                                                  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount GoodJob::Engine => 'good_job'
  mount ActionCable.server => '/cable'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ show edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy!

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "Expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:name, :description, :amount, :activity_id)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Name:</strong>
    <%= expense.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= expense.description %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

  <p>
    <strong>Activity:</strong>
    <%= expense.activity_id %>
  </p>

</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :activity_id, style: "display: block" %>
    <%= form.text_field :activity_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", activity_expenses_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
    <p>
      <%= link_to "Show this expense", expense %>
    </p>
  <% end %>
</div>

<%= link_to "New expense", new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Back to expenses", activity_expenses_path %>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", activity_expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>